import './js/burgerMenu';
import './js/features';
import './js/domination';
import './js/events';
import './js/optimized';
import './js/screen';
import './js/faq';
import './js/cookie';
import './js/cta';
